### ISSUE TITLE
Please provide build instructions

### ISSUE THREAD

**Issue by pangard** [yochaigal/cairn#117]
Hello:

I downloaded the repo and tried to build the documents:

- `cairn/scripts/ebook/build-epub.sh` worked after changing some absolute paths.
- Do you have commands for building the cairn pdf instead of an epub?
- `cairn/scripts/build-bestiary-letter.sh` also required changing some absolute paths, but then required `cairn-bestiary.tex`,  which is not in the repo :-/

Thanks for sharing!

**Comment by yochaigal** [comment]
cairn-bestairy.tex is just a renamed letter.tex from the sources folder. You can see the change in the script.

I plan on reworking the whole script in the future, I just don't have time!

**Comment by pangard** [comment]
True, just fixing the paths in the scripts build the bestiary fine. I could also build a pdf with the ruleset, but it looks like some options are missing to get the true Cairn SRD :-/

Thanks again. It's a good starting point anyway.

**Comment by yochaigal** [comment]
When the Cairn 2e SRD goes live I'll probably setup some more robust means to "build" the rules into various formats (which should allow for hacking). Right now my main focus is on the app, writing the warden's guide, and putting out adventures!

But I'll get around to it eventually :).

**Comment by pangard** [comment]
A humble suggestion: maybe build instructions and examples for building adventures might help you get more adventures into the system...

**Comment by yochaigal** [comment]
Of course! But presently I'm working on a lot of other stuff, and I have a full-time job, I'm a parent, etc. I do have a style guide for adding adventures that sees pretty heavy use! Is there something you think could be different about that?
I also have a Build An Adventure Site page on the website, and I'll have a TON in the upcoming second edition (launching March 2024). I've already got a ton here in the WIP section you can see for yourself!

**Comment by pangard** [comment]
Oh, thanks a lot, I'll keep browsing the available material :-) ...
