### ISSUE TITLE
Docs broken link

### ISSUE THREAD

**Issue by carsonbird** [yochaigal/cairn#135]
This link is broken, needs the /player-guide path in the middle.

The link below links to the code with the broken link inside it:

https://github.com/yochaigal/cairn/blob/main/second-edition%2Fplayers-guide%2Fcharacter-creation.md#L47

There are likely other similar broken links if this sub-page was added later, or something.

**Comment by yochaigal** [comment]
Looks like it was only this link that missed the players-guide stub, so that's good.
Thanks!

**Comment by carsonbird** [comment]
Looks like the healing link right above it also isn't quite right, the anchor isn't right. Should be https://cairnrpg.com/second-edition/players-guide/core-rules/#healing--recovery, not just #healing

**Comment by yochaigal** [comment]
Fixed!
