### ISSUE TITLE
Typo in 3rd party hack "Classic Classes"

### ISSUE THREAD

**Issue by Argavyon** [yochaigal/cairn#61]
https://github.com/yochaigal/cairn/blob/3c11d275857a5526c4ece50635981acdacdd5b93/hacks/third-party/classic-classes.md?plain=1#L32

The part `Roll 1d0+10` should probably read `Roll 1d10+10` (or whatever correct dice size).

**Comment by yochaigal** [comment]
Fixed, thanks!
