### ISSUE TITLE
Scars discrepency in SRD

### ISSUE THREAD

**Issue by lingawakad** [yochaigal/cairn#65]
The SRD section on Hit Protection - https://cairnrpg.com/cairn-srd/#hit-protection - says to roll for scars when HP is brought to 0, but the Scars table - https://cairnrpg.com/cairn-srd/#scars-1 - says the result is the total of damage taken.

**Comment by yochaigal** [comment]
I'm aware of the discrepancy; however the SRD is 100% equivalent to the present PDF. I'm going to fix it in the next major PDF update (it takes a few hours of work to update the various stores that sell it PoD so I like to space out my fixes). 

Thanks!

**Comment by yochaigal** [comment]
One more thing:
You do in fact roll on the Scars table, just in the entry, not the table itself. It's super confusing, obviously. But rolling does happen!

**Comment by lingawakad** [comment]
ahhh, got it. sorry for the unnecessary issue. thanks!
