### ISSUE TITLE
Barrow of the Elf King conversion - 3. The Grave Slab

### ISSUE THREAD

**Issue by Arnklit** [yochaigal/cairn#67]
Might have missed something, but I think maybe it should be suggested that the time for the hourglass is shorter.

In the adventure it's set to 10 minutes. But Cairn's combat rounds are mentioned to be roughly 10 seconds. That would make the combat last 60 rounds before the time ran out?

**Comment by yochaigal** [comment]
It might, yeah. But it won't - and no one is tracking it, esp in a game like Cairn. The truth is that time is mercurial in rules-lite systems; if you needed to run it "by the book" you could just limit it to 10 minutes of in-game time or something.

**Comment by Arnklit** [comment]
Yeah the 10 minute real time thing sounds like a fun idea. Closing.
